import Head from 'next/head'
import { useState } from 'react'
import { DragDropContext, Draggable, Droppable } from 'react-beautiful-dnd'

const data =[
  {
    id:"0",
    name:"Luffy"
  },
  {
    id:"1",
    name:"Zoro"
  },
  {
    id:"2",
    name:"Sanji"
  },
  {
    id:"3",
    name:"Ussop"
  },
  {
    id:"4",
    name:"Nami"
  }
]

export default function Home() {

  const [characters,setCharacters]= useState(data)

  function handleDrag(result){
    console.log(result)

    const temp = Array.from(characters)
    const [reorderedItem] = temp.splice(result.source.index,1)
    temp.splice(result.destination.index,0,reorderedItem)

    setCharacters(temp)
  }


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="list-cont">
        <DragDropContext onDragEnd={handleDrag}>
          <Droppable droppableId="characters">
            {
              (provided)=>(
                <div className="list" {...provided.droppableProps} ref={provided.innerRef}>
                  {
                    characters.map((el,idx)=>(
                      <Draggable key={el.id} draggableId={el.id} index={idx} >
                        {
                          (provided)=>(
                            <div className="list-item" {...provided.draggableProps} {...provided.dragHandleProps} ref={provided.innerRef} >
                              <p>id : {el.id}</p>
                              <h3>{el.name}</h3>
                            </div>
                          )
                        }
                      </Draggable>
                    ))
                  }
                  {provided.placeholder}
                </div>
              )
            }
            
          </Droppable>
        </DragDropContext>
      </main>
    </>
  )
}
